# Generated by Django 4.2.4 on 2023-12-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=64)),
                ('description', models.TextField(max_length=2000)),
                ('imageURL', models.TextField(blank=True, max_length=64)),
            ],
        ),
    ]
