# Generated by Django 4.2.4 on 2023-12-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='categories',
            field=models.CharField(choices=[('TO', 'Toys'), ('HO', 'Home')], default='TO', max_length=2),
        ),
    ]
